/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/app-footer.vue')['default']
    AppHeader: typeof import('./../components/app-header.vue')['default']
    CodeInput: typeof import('./../components/code-input.vue')['default']
  }
}
